from typing import List, Tuple
from app.invoices_generator.core.bank import bank
from app.invoices_generator.core.enumerates.banks import banks
from app.invoices_generator.core.enumerates.company_type import company_type
from app.invoices_generator.core.enumerates.payment_type import payment_type


company_names: list[str] = [
    "Novák",
    "Pekařství U Rohlíku",
    "AlfaTech",
    "Stavebniny Horák",
    "IT Solutions",
    "Květinářství Rose",
    "Omega Consulting",
    "Kavárna U Mostu",
    "Autoservis Marek",
    "Design Studio Line",
    "Restaurace Pod Lipami",
    "TravelWorld",
    "EcoBuild",
    "Grafika Plus",
    "Servis 24",
    "Bio Farma Dvůr",
    "Tiskárna Praha",
    "CleanHome",
    "EnergyPro",
    "BuildPoint",
    "MegaElectro",
    "Agro CZ",
    "Wellness Centrum Aurora",
    "FastFood Express",
    "Hotel Panorama",
    "LogisTrans",
    "FinExpert",
    "BeautySalon Glamour",
    "AutoMoto Club",
    "Sportovní centrum Fit",
    "ElektroServis",
    "Architektura+",
    "SoftWorks",
    "MobilWorld",
    "GreenTech",
    "Hračky Veselý Medvěd",
    "Nábytek Styl",
    "Lékárna U Anděla",
    "Restaurace Zlatý Lev",
    "Cestovní kancelář Slunce",
    "IT Partners",
    "Bytové Studio Elegant",
    "Fresh Market",
    "Wine & Spirits",
    "Studio Krása",
    "Dřevostavby CZ",
    "HydroSystems",
    "Kancelářské Centrum",
    "HobbyMarket",
    "PetShop Happy Paw",
    "SilverStone Architects",
    "NextGen Solutions",
    "BlueSky Software",
    "EuroTrans",
    "ProfiStav",
    "FreshFood Delivery",
    "Baker’s Choice",
    "Sunny Café",
    "Dream Travel",
    "EcoGarden",
    "QuickFix Servis",
    "MediaHouse",
    "EventPro",
    "HealthCare Plus",
    "EduCenter",
    "DataMasters",
    "PrintLab",
    "SmartAuto",
    "HomeDesign",
    "TechnoPark",
    "PowerLine Systems",
    "FarmFresh",
    "WoodWorks",
    "Skyline Construction",
    "SolarFuture",
    "Coffee Lovers",
    "Happy Kids",
    "Zlatnictví Rubin",
    "AutoRent",
    "Global Consulting",
    "LifeStyle Studio",
    "UrbanFit",
    "Relax Spa",
    "FashionPoint",
    "ElectroWorld",
    "BeautyBox",
    "BioTech Labs",
    "LogiWare",
    "EventMasters",
    "Studio Vision",
    "SoundWorks",
    "GreenPower",
    "Food4You",
    "LuxHotel",
    "SafeGuard Security",
    "Alpha Print",
    "MegaShop",
    "AutoClinic",
    "CodeFactory",
    "CyberNet",
    "Shop&Go",
    "GardenLife",
    "Happy Pets",
    "KidsWorld",
    "CarWash Express",
    "MoveIt Transport",
    "BetterBuild",
    "ProEnergy",
    "WineHouse",
    "Happy Bakery",
    "Crystal Spa",
    "FitZone",
    "Royal Café",
    "Dream House",
    "EcoLiving",
    "NextStep Education",
    "TravelStar",
    "GastroPoint",
    "CineMax",
    "UrbanMarket",
    "WorkHub",
    "PrintZone",
    "Kavárna Slunce",
    "TeaTime",
    "FoodBox",
    "Office Pro",
    "StavProjekty",
    "Lumen Design",
    "Build&Fix",
    "PetFarm",
    "SkyNet Solutions",
    "EcoFarm",
    "CoffeeCorner",
    "Studio Art",
    "SoundClub",
    "ProFoto",
    "GardenPro",
    "MegaMarket",
    "Kancelář+",
    "StudioLine",
    "EduPro",
    "MoveUp",
    "StepIn Fashion",
    "House&Home",
    "SolarHouse",
    "FutureTech",
    "Royal Travel",
    "KingFood",
    "BeautyLine",
    "BodyCare",
    "BikeWorld",
    "SkiResort",
    "NextBuild",
    "FreshBar",
    "PizzaTime",
    "Urban Bistro",
    "Wine & Dine",
    "Hotel Classic",
    "CodeLab",
    "MediaPro",
    "PrintPro",
    "GreenWorks",
    "HouseFit",
    "SuperFood",
    "SkyTravel",
    "Relax Point",
    "StudioX",
    "HappyLand",
    "EduSmart",
    "CoffeeDream",
    "BodyFit",
    "CarExpert",
    "BuildMax",
    "DesignLab",
    "ElectroFix",
    "FutureEnergy",
    "CityHotel",
    "NextCar",
    "GardenStyle",
    "ProTools",
    "LifeFit",
    "HomeMarket",
    "Tea&Coffee",
    "EventCity",
    "GlobalTrans",
    "MediaGroup",
    "TechVision",
    "QuickBuild",
    "MegaPrint",
    "Royal Garden",
    "LuxuryHouse",
    "PetClinic",
    "Studio Glam",
    "AutoPro",
    "TravelPoint",
    "GastroLine",
    "SoftVision",
    "FoodTime",
    "UrbanStyle",
    "SkyBar",
    "DataSolutions",
    "MoveMore",
    "BetterLife",
    "DreamSpa",
    "BuildCity",
    "PrintHouse",
    "WineGarden",
    "Hotel Lux",
    "EcoPoint",
    "CarPoint",
    "WorkCenter",
    "NextGen Build",
    "SolarEnergy",
    "FreshStyle",
    "FashionLine",
    "FoodExpress",
    "SafeHome",
    "EduLine",
    "MoveCity",
    "ProMarket",
    "Urban Café",
    "SmartSolutions",
    "DataPro",
    "AutoRent Plus",
    "Studio Perfect",
    "MediaHouse Pro",
    "BodyLine",
    "GardenStar",
    "GreenFuture",
    "RelaxWorld",
    "BuildOne",
    "Hotel Europa",
]

person_names: list[str] = [
    "Jan Novotný",
    "Lucie Malá",
    "Petr Dvořák",
    "Eva Králová",
    "Tomáš Říha",
    "Helena Veselá",
    "Martin Pokorný",
    "Barbora Černá",
    "Karel Svoboda",
    "Jana Veselá",
    "Michal Procházka",
    "Hana Fialová",
    "David Kučera",
    "Petra Jelínková",
    "Roman Marek",
    "Veronika Hrušková",
    "Ondřej Král",
    "Tereza Němcová",
    "Radek Bláha",
    "Alena Bartošová",
    "Jakub Štěpánek",
    "Monika Čermáková",
    "Filip Havel",
    "Klára Pokorná",
    "Daniel Mareš",
    "Adéla Dvořáková",
    "Štěpán Zeman",
    "Markéta Urbanová",
    "Josef Holub",
    "Nikola Křížová",
    "Viktor Beneš",
    "Sabina Kolářová",
    "Marek Nový",
    "Zuzana Havlíková",
    "Václav Hrubý",
    "Aneta Richterová",
    "Stanislav Říha",
    "Lenka Slavíková",
    "Patrik Janda",
    "Iva Šimková",
    "Dominik Veselý",
    "Andrea Kučerová",
    "Jaroslav Kratochvíl",
    "Nikol Řeháková",
    "Lukáš Švec",
    "Eliška Moravcová",
    "Miloš Jelínek",
    "Kristýna Matoušková",
    "Zdeněk Novotný",
    "Simona Marešová",
    "Richard Černý",
    "Marcela Králová",
    "Adam Kříž",
    "Gabriela Štěpánková",
    "Roman Kučera",
    "Iveta Dvořáková",
    "Šimon Horák",
    "Karolína Šimková",
    "Dalibor Beneš",
    "Renata Konečná",
    "Pavel Pokorný",
    "Monika Malá",
    "Aleš Svoboda",
    "Sandra Čechová",
    "Michal Krejčí",
    "Natálie Štěrbová",
    "Bohumil Krása",
    "Lucie Hrdličková",
    "Otakar Bláha",
    "Denisa Veselá",
    "Radim Konečný",
    "Ivana Vávrová",
    "Kamil Říha",
    "Markéta Kolářová",
    "Tomáš Beneš",
    "Jitka Malíková",
    "Libor Hruška",
    "Aneta Novotná",
    "Vít Holý",
    "Lucie Veselá",
    "Šárka Němcová",
    "Matěj Král",
    "Linda Fialová",
    "Jiří Svoboda",
    "Eva Holubová",
    "Robert Černý",
    "Andrea Havelková",
    "Ondřej Novák",
    "Michaela Pokorná",
    "Radovan Štěpánek",
    "Jana Kratochvílová",
    "Aleš Marek",
    "Kateřina Dvořáková",
    "Tomáš Zima",
    "Klára Konečná",
    "David Čech",
    "Iveta Kolářová",
    "Jakub Nový",
    "Tereza Svobodová",
    "František Král",
    "Marta Jelínková",
    "Lukáš Horák",
    "Michaela Malá",
    "Pavel Hruška",
    "Karolína Marešová",
    "Jan Zeman",
    "Veronika Holubová",
    "Daniel Procházka",
    "Lenka Benešová",
    "Karel Kratochvíl",
    "Jana Matoušková",
    "Filip Marek",
    "Alžběta Veselá",
    "Roman Kříž",
    "Petra Svobodová",
    "Stanislav Čech",
    "Denisa Urbanová",
    "Miroslav Pokorný",
    "Tereza Havlíková",
    "Tomáš Richter",
    "Eliška Hrušková",
    "Patrik Bláha",
    "Jana Bartošová",
    "Jakub Němec",
    "Lucie Vávrová",
    "David Zeman",
    "Iveta Černá",
    "Michal Kolář",
    "Barbora Králová",
    "Aleš Novák",
    "Nikola Kučerová",
    "Vladimír Mareš",
    "Andrea Malá",
    "Petr Král",
    "Jana Procházková",
    "Karel Veselý",
    "Tereza Jelínková",
    "Ondřej Malý",
    "Eva Svobodová",
    "Radek Matoušek",
    "Michaela Pokorná",
    "Roman Nový",
    "Kateřina Kučerová",
    "Josef Novák",
    "Alena Černá",
    "Martin Kolář",
    "Markéta Marešová",
    "Petr Svoboda",
    "Veronika Pokorná",
    "Jakub Dvořák",
    "Lucie Králová",
    "Jan Beneš",
    "Zuzana Černá",
    "Miroslav Svoboda",
    "Klára Veselá",
    "Lukáš Procházka",
    "Barbora Kratochvílová",
    "Radim Novotný",
    "Eva Křížová",
    "Ondřej Čech",
    "Tereza Marešová",
    "Kamil Král",
    "Petra Veselá",
    "Vojtěch Malý",
    "Karolína Svobodová",
    "Richard Dvořák",
    "Aneta Pokorná",
    "Štěpán Kučera",
    "Nikola Kratochvílová",
    "Daniel Bláha",
    "Simona Novotná",
    "Patrik Holub",
    "Lucie Marešová",
    "Radovan Nový",
    "Michaela Svobodová",
    "David Král",
    "Andrea Veselá",
    "Roman Malý",
    "Klára Jelínková",
    "Filip Čech",
    "Jana Kučerová",
    "Tomáš Kratochvíl",
    "Barbora Novotná",
    "Martin Svoboda",
    "Kateřina Malá",
    "Jakub Pokorný",
    "Tereza Dvořáková",
    "Pavel Nový",
    "Veronika Králová",
    "Lukáš Mareš",
    "Aneta Černá",
    "Josef Kučera",
    "Lucie Nováková",
    "Jan Malý",
    "Eva Pokorná",
    "Miroslav Dvořák",
    "Andrea Čechová",
    "Karel Novotný",
    "Jana Bláhová",
    "Radek Kučera",
    "Petra Králová",
    "Ondřej Veselý",
    "Barbora Malá",
    "Vladimír Dvořák",
    "Michaela Novotná",
    "Filip Svoboda",
    "Zuzana Pokorná",
    "Tomáš Král",
    "Lenka Nováková",
]


street_names: list[str] = [
    "Nádražní 12",
    "Masarykova 45",
    "Hlavní 128",
    "Dlouhá 78",
    "Smetanova 5",
    "Komenského 33",
    "Jiráskova 9",
    "Tyršova 88",
    "Polní 16",
    "Školní 2",
    "Lipová 41",
    "Husova 7",
    "Sadová 55",
    "Sluneční 23",
    "Mlýnská 10",
    "Březová 19",
    "Růžová 4",
    "U Trati 15",
    "Zahradní 3",
    "Pod Lesem 29",
    "Na Výsluní 8",
    "U Pivovaru 21",
    "Křižíkova 77",
    "Pod Hůrkou 14",
    "Lesní 45",
    "Kovářská 12",
    "Na Láně 67",
    "Úzká 3",
    "Na Hrázi 22",
    "Loučná 31",
    "Borová 11",
    "Na Skále 9",
    "Za Školou 18",
    "U Potoka 6",
    "Ke Mlýnu 27",
    "Na Vinici 44",
    "Sladová 15",
    "V Aleji 20",
    "Za Parkem 30",
    "Horská 14",
    "Na Kopci 38",
    "U Hřiště 55",
    "Sportovní 7",
    "Květnová 12",
    "Lípa 3",
    "U Jezera 17",
    "Kamenická 42",
    "Dolní 8",
    "Horní 26",
    "U Rybníka 9",
    "Kostelní 4",
    "Mostní 21",
    "Stará 33",
    "Nová 11",
    "Na Stráni 19",
    "U Lomu 40",
    "Skalní 12",
    "Na Výhledu 14",
    "Pod Kostelem 18",
    "Na Louce 6",
    "Jabloňová 25",
    "Třešňová 29",
    "Višňová 5",
    "Jasanová 13",
    "Buková 22",
    "Hrušková 17",
    "Švestková 8",
    "Meruňková 10",
    "Ovocná 27",
    "Zimní 3",
    "Letní 15",
    "Jarní 9",
    "Podzimní 11",
    "Čechova 36",
    "Sladkovského 7",
    "Erbenova 14",
    "Nerudova 20",
    "Palackého 19",
    "Riegrova 8",
    "Fügnerova 6",
    "Mánesova 31",
    "Sokolská 42",
    "U Stadionu 25",
    "Na Valech 12",
    "Na Pískách 16",
    "Růžodolská 14",
    "Pod Hrází 28",
    "K Hřišti 10",
    "Pod Zámkem 19",
    "Za Kostelem 11",
    "Dukelská 44",
    "Legionářská 18",
    "Revoluční 21",
    "28. října 55",
    "17. listopadu 60",
    "5. května 40",
    "1. máje 13",
    "8. května 17",
    "30. dubna 8",
    "Pod Sadem 9",
    "U Stromovky 27",
    "Na Balkáně 6",
    "Za Tratí 12",
    "V Zahradách 19",
    "U Lesa 7",
    "Na Poříčí 22",
    "Karlova 18",
    "Václavská 15",
    "Pražská 44",
    "Brněnská 31",
    "Ostravská 29",
    "Plzeňská 25",
    "Olomoucká 36",
    "Českobudějovická 12",
    "Hradecká 18",
    "Pardubická 22",
    "Zlínská 16",
    "Karlovarská 33",
    "Teplická 19",
    "Opavská 28",
    "Jihlavská 14",
    "Ústecká 24",
    "Mladoboleslavská 20",
    "Kladenská 21",
    "Frýdecká 10",
    "Karvinská 8",
    "Havířovská 9",
    "Třinecká 17",
    "Liberecká 23",
    "Litvínovská 11",
    "Mostecká 15",
    "Chomutovská 13",
    "Trutnovská 18",
    "Kolínská 7",
    "Chebská 19",
    "Jablonecká 14",
    "Břeclavská 9",
    "Kroměřížská 8",
    "Šumperská 10",
    "Sokolovská 32",
    "Vsetínská 17",
    "Žďárská 12",
    "Táboritská 14",
    "Příbramská 6",
    "Uherskohradišťská 20",
    "Prostějovská 11",
    "Hodonínská 13",
    "Třebíčská 15",
    "Novojičínská 10",
    "Litoměřická 9",
    "Náchodská 14",
    "Chrudimská 12",
    "Jindřichohradecká 8",
    "Strakonická 22",
    "Písecká 7",
    "Klatovská 14",
    "Rokycanská 10",
    "Blanenská 11",
    "Boskovická 9",
    "Vyškovská 13",
    "Bruntálská 8",
    "Krnovská 15",
    "Šternberská 6",
    "Uničovská 12",
    "Holešovská 14",
    "Valašská 10",
    "Rožnovská 18",
    "Valašskomeziříčská 7",
    "Hranická 13",
    "Vsetínská 16",
    "Poděbradská 25",
    "Kutnohorská 18",
    "Nymburská 14",
    "Berounská 12",
    "Rakovnícká 9",
    "Mělnická 15",
    "Kralupská 11",
    "Čelákovická 8",
    "Brandýská 13",
    "Říčanská 14",
    "Benešovská 10",
    "Sedlčanská 7",
    "Táboritů 19",
    "Pelhrimovská 13",
    "Pacovská 12",
    "Dačická 8",
    "Telčská 10",
    "Moravská 17",
    "Slovenská 16",
    "Polská 18",
    "Rakouská 14",
    "Německá 15",
]


city_names: list[str] = [
    "Praha",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "České Budějovice",
    "Hradec Králové",
    "Ústí nad Labem",
    "Pardubice",
    "Zlín",
    "Karlovy Vary",
    "Jihlava",
    "Teplice",
    "Opava",
    "Frýdek-Místek",
    "Karviná",
    "Havířov",
    "Kladno",
    "Mladá Boleslav",
    "Tábor",
    "Příbram",
    "Uherské Hradiště",
    "Prostějov",
    "Chomutov",
    "Trutnov",
    "Cheb",
    "Kolín",
    "Jablonec nad Nisou",
    "Most",
    "Nový Jičín",
    "Třebíč",
    "Břeclav",
    "Kroměříž",
    "Litoměřice",
    "Šumperk",
    "Sokolov",
    "Vsetín",
    "Žďár nad Sázavou",
    "Hodonín",
    "Kutná Hora",
    "Náchod",
    "Chrudim",
    "Jindřichův Hradec",
    "Strakonice",
    "Písek",
    "Klatovy",
    "Rokycany",
    "Blansko",
    "Vyškov",
    "Krnov",
    "Bruntál",
    "Uherský Brod",
    "Znojmo",
    "Český Krumlov",
    "Prachatice",
    "Pelhřimov",
    "Žatec",
    "Rakovník",
    "Beroun",
    "Mělník",
    "Kralupy nad Vltavou",
    "Čelákovice",
    "Brandýs nad Labem",
    "Říčany",
    "Benešov",
    "Sedlčany",
    "Poděbrady",
    "Nymburk",
    "Hranice",
    "Rožnov pod Radhoštěm",
    "Valašské Meziříčí",
    "Holešov",
    "Valašské Klobouky",
    "Šternberk",
    "Uničov",
    "Boskovice",
    "Moravská Třebová",
    "Lanškroun",
    "Litomyšl",
    "Vysoké Mýto",
    "Svitavy",
    "Nové Město na Moravě",
    "Velké Meziříčí",
    "Česká Lípa",
    "Turnov",
    "Semily",
    "Jičín",
    "Dvůr Králové nad Labem",
    "Jaroměř",
    "Nová Paka",
    "Rychnov nad Kněžnou",
    "Dobruška",
    "Hořice",
    "Louny",
    "Kadaň",
    "Litvínov",
    "Mostkovice",
    "Planá",
    "Mariánské Lázně",
    "Františkovy Lázně",
    "Aš",
    "Sušice",
    "Horažďovice",
    "Kdyně",
    "Domažlice",
    "Tachov",
    "Stříbro",
    "Krupka",
    "Roudnice nad Labem",
    "Lovosice",
    "Kadaň",
    "Vrchlabí",
    "Harrachov",
    "Špindlerův Mlýn",
    "Janské Lázně",
    "Pec pod Sněžkou",
    "Žacléř",
    "Hostinné",
    "Jilemnice",
    "Nové Město pod Smrkem",
    "Hejnice",
    "Frenštát pod Radhoštěm",
    "Kopřivnice",
    "Studénka",
    "Orlová",
    "Rychvald",
    "Bohumín",
    "Hlučín",
    "Kravaře",
    "Vrbno pod Pradědem",
    "Javorník",
    "Šumperk",
    "Zábřeh",
    "Mohelnice",
    "Konice",
    "Proseč",
    "Skuteč",
    "Hlinsko",
    "Chotěboř",
    "Ledeč nad Sázavou",
    "Světlá nad Sázavou",
    "Humpolec",
    "Telč",
    "Dačice",
    "Slavonice",
    "Pacov",
    "Počátky",
    "Sezimovo Ústí",
    "Soběslav",
    "Veselí nad Lužnicí",
    "Týn nad Vltavou",
    "Vodňany",
    "Blatná",
    "Horažďovice",
    "Nepomuk",
    "Klatovy",
    "Železná Ruda",
    "Kašperské Hory",
    "Volary",
    "Vimperk",
    "Horní Planá",
    "Česká Třebová",
    "Třeboň",
    "Chotěboř",
    "Moravský Krumlov",
    "Ivančice",
    "Rosice",
    "Kuřim",
    "Tišnov",
    "Židlochovice",
    "Pohořelice",
    "Mikulov",
    "Hustopeče",
    "Bystřice nad Pernštejnem",
    "Nedvědice",
    "Kunštát",
    "Letovice",
    "Adamov",
    "Rájec-Jestřebí",
    "Velká Bíteš",
    "Slavkov u Brna",
    "Bučovice",
    "Kyjov",
    "Bzenec",
    "Veselí nad Moravou",
    "Strážnice",
    "Moravská Nová Ves",
    "Tvrdonice",
    "Lanžhot",
    "Valtice",
    "Lednice",
    "Děčín",
    "Teplice nad Metují",
    "Broumov",
    "Police nad Metují",
]

company_types:list[company_type] = [ct for ct in company_type]

banks_:list[bank] = [bn.value for bn in banks]
payments:list[payment_type] = [tp for tp in payment_type]
vat_percentages:list[int] = [0, 12, 21]

item_names: list[str] = [
    # Elektronika
    "Notebook", "Mobilní telefon", "Tablet", "Monitor", "Kancelářská židle",
    "Psací stůl", "Kávovar", "Tiskárna", "Skener", "Projektor",
    "Sluchátka", "Reproduktor", "Televize", "Myš", "Klávesnice",
    "Externí disk", "USB flash disk", "Router", "Switch", "Server",
    "Digitální fotoaparát", "Objektiv", "3D tiskárna", "Drukovací papír", "Toner",
    "Smart hodinky", "Elektrická koloběžka", "Kolo", "Herní konzole", "Stolní počítač",
    "Herní myš", "Herní klávesnice", "Herní sluchátka", "VR brýle", "Powerbanka",
    "Blu-ray přehrávač", "DVD přehrávač", "Set-top box", "Wi-Fi extender", "Mikrofon",
    "Webkamera", "GPS navigace", "Smart domácí asistent", "Mini PC", "NAS server",

    # Domácnost
    "Chladnička", "Pračka", "Mikrovlnná trouba", "Vysavač", "Klimatizace",
    "Lampička", "Regál", "Policová skříň", "Postel", "Matrace",
    "Povlečení", "Polštář", "Přikrývka", "Noční stolek", "Koberec",
    "Závěsy", "Žaluzie", "Kuchyňský stůl", "Židle", "Komoda",
    "Šatní skříň", "Botník", "Zahradní nábytek", "Gril", "Trampolína",
    "Bazén", "Vířivka", "Dětská postýlka", "Kočárek", "Dětská židlička",
    "Spacák", "Stan", "Karimatka", "Campingová svítilna", "Grilovací sada",
    "Žehlička", "Sušička prádla", "Mixér", "Kuchyňský robot", "Rychlovarná konvice",

    # Oblečení a doplňky
    "Tričko", "Košile", "Kalhoty", "Bunda", "Kabát",
    "Sako", "Sukně", "Šaty", "Kraťasy", "Mikina",
    "Svetr", "Čepice", "Kšiltovka", "Šála", "Rukavice",
    "Ponožky", "Boty", "Tenisky", "Sandály", "Pantofle",
    "Kabelka", "Batoh", "Peněženka", "Pásek", "Sluneční brýle",
    "Hodinky", "Náušnice", "Náramek", "Prsten", "Řetízek",

    # Sport
    "Fotbalový míč", "Basketbalový míč", "Volejbalový míč", "Tenisová raketa", "Badmintonová raketa",
    "Pingpongová pálka", "Lyže", "Snowboard", "Helma", "Chrániče",
    "Koloběžka", "Běžky", "Skateboard", "Longboard", "Hokejka",
    "Brusle", "Florbalová hůl", "Sportovní taška", "Švihadlo", "Činky",
    "Běžecký pás", "Rotoped", "Posilovací lavice", "Jóga podložka", "Boxovací pytel",

    # Kancelář a škola
    "Sešit", "Kniha", "Diář", "Poznámkový blok", "Kalkulačka",
    "Kancelářské potřeby", "Propiska", "Fixy", "Zvýrazňovač", "Ořezávátko",
    "Pravítko", "Kružítko", "Sponky", "Lepící páska", "Obálky",
    "Šanon", "Pořadač", "Archivační box", "Tabule", "Korková nástěnka",
    "Flipchart", "Projektorové plátno", "Laserové ukazovátko", "USB kabel", "HDMI kabel",

    # Potraviny a nápoje
    "Chléb", "Rohlík", "Croissant", "Koláč", "Sušenky",
    "Čokoláda", "Bonbóny", "Dort", "Med", "Marmeláda",
    "Káva", "Čaj", "Energetický nápoj", "Minerální voda", "Pivo",
    "Víno", "Destilát", "Džus", "Smoothie", "Sirup",
    "Maso", "Šunka", "Sýr", "Máslo", "Jogurt",
    "Mléko", "Těstoviny", "Rýže", "Mouka", "Cukr",
    "Olej", "Olivový olej", "Ocet", "Kečup", "Hořčice",

    # Služby
    "Poradenství", "Úklidové služby", "Grafický návrh", "Vývoj mobilní aplikace", "Tisk vizitek",
    "Tisk katalogů", "Marketingová kampaň", "Fotografické služby", "Catering", "Školení zaměstnanců",
    "Doprava – kurýr", "Právní služby", "Účetnictví", "Stavební práce", "Instalatérské práce",
    "Elektrikářské služby", "Kadeřnictví", "Kosmetika", "Masáže", "Wellness procedury",
    "Fitness trénink", "Online kurz", "Doučování", "IT správa", "Servis domácích spotřebičů",
]


fonts:List[Tuple[str,str]] = [("OpenSans-Regular.ttf","OpenSans-Bold.ttf"),
                              ("ARIAL.ttf", "ARIALB.ttf"),
                              ("Helvetica.ttf","Helvetica-Bold.ttf"),
                              ("Times New Roman.ttf","Times New Roman - Bold.ttf")]