from PIL.ImageDraw import ImageDraw
from abc import ABC, abstractmethod
import random

from common.invoice.models.Invoice import Invoice
from common.invoice.models.InvoiceData import InvoiceData
from common.invoice.renderers.TextRenderer import TextRenderer

from common.data.InvoiceComponent import InvoiceComponent
from common.enumerates.SpanTag import SpanTag
from common.utils.utilities import mm, load_font, get_iou, text_width, get_tesseract_words, get_random_style, draw_styled_rect, get_rand_date
from common.utils.consts import INK, MUTED, LINE, LINE_MID, LINE_STRONG, BG, SUBTLE_BG, FOOT_BG, BOX_BG, TMOBILE_PINK
from common.utils.utilities import safe, fmt_money



class LoremE(InvoiceComponent):

    def render(textRenderer:TextRenderer, data:InvoiceData, invoice:Invoice, x: int, y: int, **kwargs):
        d: ImageDraw = ImageDraw(invoice.image)
        max_w = kwargs.get("width", mm(85))
        start_y = y

        # 1. NADPIS (Seriózní, administrativní)
        titles = ["DOPLŇUJÍCÍ INFORMACE", "OBCHODNÍ SDĚLENÍ A VOP", "ADMINISTRATIVNÍ POZNÁMKY"]
        textRenderer._text(invoice, (x, y), text=random.choice(titles), font=textRenderer._f8b, fill=INK)
        y += mm(4)

        # 2. ZÁSOBNÍK TEXTOVÉ VATY
        # Rozděleno na různé okruhy pro maximální variabilitu
        text_pool = [
            # Právní vata
            f"Smluvní vztah mezi dodavatelem a odběratelem se řídí zákonem č. 89/2012 Sb., občanský zákoník, ve znění pozdějších předpisů. "
            f"Tento doklad byl vystaven v informačním systému verze {random.randint(1,9)}.{random.randint(10,99)} dne {get_rand_date()}. ",
            
            # Reklamace a vracení
            f"Případné reklamace na množství nebo viditelné vady plnění musí být uplatněny nejpozději do {get_rand_date()} u pověřeného pracovníka. "
            f"Zboží zůstává až do úplného zaplacení kupní ceny ve vlastnictví prodávajícího podle výhrady vlastnictví dle § 2132 OZ. ",
            
            # Platební a bankovní vata
            f"Při platbě převodem uvádějte variabilní symbol uvedený v záhlaví. Bez správného VS nelze platbu automaticky spárovat. "
            f"V případě prodlení s platbou po datu {get_rand_date()} si dodavatel vyhrazuje právo účtovat smluvní pokutu ve výši 0.05 % z dlužné částky za každý den prodlení. ",
            
            # Eko a Systémové kecy
            f"Myslíme na životní prostředí, proto tento doklad zasíláme přednostně v elektronické podobě. "
            f"Digitálně podepsáno certifikátem autority k datu {get_rand_date()}. "
            f"Kontrolní součet dokumentu (Hash): {hex(random.getrandbits(32))}. ",
            
            # Marketing a loajalita
            f"Děkujeme za váš nákup! Vaše spokojenost je pro nás prioritou. "
            f"Nezapomeňte využít slevový kupón 'LETO2026' při vaší příští objednávce do {get_rand_date()}. "
            f"Navštivte naše webové stránky a zjistěte více o našem věrnostním programu a aktuálních akcích."
        ]

        # Vybereme náhodný počet odstavců (2 až 4) a spojíme je
        random.shuffle(text_pool)
        long_text = " ".join(text_pool[:random.randint(2, 4)])

        # 3. WORD-WRAP S JUSTIFY (Simulace bloku)
        words = long_text.split(' ')
        current_line = ""
        
        for word in words:
            test_line = current_line + word + " "
            if text_width(test_line, textRenderer._f8) < max_w:
                current_line = test_line
            else:
                # Vykreslení řádku
                textRenderer._text(invoice, (x, y), text=current_line.strip(), font=textRenderer._f8, fill=MUTED)
                y += mm(3.2) # Husté řádkování
                current_line = word + " "
        
        # Poslední řádek
        if current_line:
            textRenderer._text(invoice, (x, y), text=current_line.strip(), font=textRenderer._f8, fill=MUTED)
            y += mm(3.2)

        # 4. PATIČKA BLOKU (Technický kód)
        y += mm(2)
        tech_info = f"Generated by system core-v2 | Stamp: {random.randint(100,999)} | Date ref: {get_rand_date()}"
        textRenderer._text(invoice, (x, y), text=tech_info, font=textRenderer._f8, fill=MUTED)

        return y + mm(5)