GROUP_OVERLAY = "overlay"
SCAN_IMAGE = "scan_image"

TOKEN_TAG = "tokens"
TOKEN_TEXT_TAG = "tokensText"

SPAN_TAG = "spans"
SPAN_TEXT_TAG = "spansText"

SEGMENT_TAG = "segments"
SEGMENT_TEXT_TAG = "segmentsText"

CREATE_TAG = "create"

RESET = "RESET"
REMOVE = "REMOVE"

CREATE_TOKEN = "CREATE_TOKEN"
CREATE_SEGMENT = "CREATE_SEGMENT"

#---------------BARVY PRO ANOTATOR -----------------

DEFAULT_TOKEN_COLOR = (0,0,0)
DEFAULT_SPAN_COLOR = (0,0,0)
DEFAULT_SEGMENT_COLOR = (160, 80, 200)

SELECTED_TOKEN_COLOR = (255,0,0)
SELECTED_SPAN_COLOR = (255,0,0)
SELECTED_SEGMENT_COLOR = (255,0,0)

SET_TOKEN_COLOR = (0,255,0)
SET_SPAN_COLOR = (0,0,255)
SET_SEGMENT_COLOR = (255,215,0)
